package br.ufba.dcc.mestrado.computacao.entities.recommender.recommendation;

public enum RecommendationEnum {
	CONTENT_BASED_RECOMMENDATION,
	COLABORATIVE_FILTERING_ITEM_BASED_RECOMMENDATION,
	COLABORATIVE_FILTERING_USER_BASED_RECOMMENDATION,
	MULTICRITERIA_LIST_BASED_RECOMMENDATION,
	MULTICRITERIA_PREDICTION_BASED_RECOMMENDATION;
}
